<?php namespace ProcessWire;

/**
 * ProcessLegalDocs — AI Generator
 *
 * Builds prompts, calls AI via Context gateway, saves Markdown files.
 */
class LegalDocsGenerator {

    /** @var array Module config */
    protected $config;

    /** @var string Base path for saving documents */
    protected $basePath;

    /** @var array Cached context data */
    protected $contextData = [];

    const DISCLAIMER = "> ⚠️ **Legal Disclaimer**\n> This document was generated by AI as a template only.\n> It does not constitute legal advice. Laws vary by jurisdiction and change over time.\n> **Consult a qualified lawyer before publishing this document on your website.**\n> *Generated by ProcessLegalDocs for ProcessWire.*";

    public function __construct(array $config, string $basePath) {
        $this->config   = $config;
        $this->basePath = rtrim($basePath, '/');
        $this->loadContextData();
    }

    // =========================================================================
    // Public API
    // =========================================================================

    public function generate(string $jurisdiction, string $documentSlug, string $langCode): array {
        set_time_limit(360); // ensure PHP doesn't kill long AI requests
        $ai = $this->getAI();
        if(!$ai) {
            return ['success' => false, 'error' => 'AI gateway not available. Install and configure the Context module.'];
        }

        $prompt = $this->buildPrompt($jurisdiction, $documentSlug, $langCode);

        $result = $ai->chat([
            'messages'    => [['role' => 'user', 'content' => $prompt]],
            'max_tokens'  => 16000,
            'temperature' => 0.3,
            'timeout'     => 300,
            'caller'      => 'ProcessLegalDocs',
        ]);

        if(isset($result['error'])) {
            return ['success' => false, 'error' => $result['error']];
        }

        $markdown = $result['content'] ?? '';
        if(empty(trim($markdown))) {
            return ['success' => false, 'error' => 'AI returned empty response.'];
        }

        $markdown = preg_replace('/^```(?:markdown)?\s*/i', '', $markdown);
        $markdown = preg_replace('/\s*```$/', '', $markdown);
        $markdown = trim($markdown);

        $saved = $this->saveDocument($jurisdiction, $documentSlug, $langCode, $markdown);

        if(!$saved) {
            return ['success' => false, 'error' => 'Failed to write file. Check directory permissions.'];
        }

        return [
            'success' => true,
            'path'    => $this->getDocumentPath($jurisdiction, $documentSlug, $langCode),
        ];
    }

    public function getDocumentPath(string $jurisdiction, string $documentSlug, string $langCode): string {
        return $this->basePath . '/' . $jurisdiction . '/' . $documentSlug . '.' . $langCode . '.md';
    }

    public function documentExists(string $jurisdiction, string $documentSlug, string $langCode): bool {
        return file_exists($this->getDocumentPath($jurisdiction, $documentSlug, $langCode));
    }

    public function getDocument(string $jurisdiction, string $documentSlug, string $langCode): string {
        $path = $this->getDocumentPath($jurisdiction, $documentSlug, $langCode);
        if(!file_exists($path)) return '';
        return file_get_contents($path);
    }

    public function getDocumentMeta(string $jurisdiction, string $documentSlug, string $langCode): array {
        $content = $this->getDocument($jurisdiction, $documentSlug, $langCode);
        return $this->parseFrontmatter($content);
    }

    public function getGeneratedDocuments(): array {
        $docs = [];
        if(!is_dir($this->basePath)) return $docs;

        foreach(glob($this->basePath . '/*', GLOB_ONLYDIR) as $jurDir) {
            $jurisdiction = basename($jurDir);
            foreach(glob($jurDir . '/*.md') as $file) {
                $filename = basename($file, '.md');
                $parts    = explode('.', $filename);
                $lang     = array_pop($parts);
                $slug     = implode('.', $parts);
                $meta     = $this->getDocumentMeta($jurisdiction, $slug, $lang);
                $docs[]   = [
                    'jurisdiction' => $jurisdiction,
                    'slug'         => $slug,
                    'lang'         => $lang,
                    'path'         => $file,
                    'size'         => filesize($file),
                    'generated'    => $meta['generated'] ?? date('Y-m-d', filemtime($file)),
                    'review_status'=> $meta['review_status'] ?? 'draft',
                    'last_reviewed'=> $meta['last_reviewed'] ?? '',
                    'title'        => $meta['title'] ?? $slug,
                ];
            }
        }

        return $docs;
    }

    public function deleteDocument(string $jurisdiction, string $documentSlug, string $langCode): bool {
        $path = $this->getDocumentPath($jurisdiction, $documentSlug, $langCode);
        if(!file_exists($path)) return false;
        return unlink($path);
    }

    public function exportZip(): string {
        $docs = $this->getGeneratedDocuments();
        if(empty($docs)) return '';

        $zipPath = $this->basePath . '/legal-docs-export-' . date('Y-m-d') . '.zip';

        if(!class_exists('ZipArchive')) return '';

        $zip = new \ZipArchive();
        if($zip->open($zipPath, \ZipArchive::CREATE | \ZipArchive::OVERWRITE) !== true) return '';

        foreach($docs as $doc) {
            if(file_exists($doc['path'])) {
                $zip->addFile($doc['path'], $doc['jurisdiction'] . '/' . basename($doc['path']));
            }
        }

        $zip->close();
        return file_exists($zipPath) ? $zipPath : '';
    }

    public function validateDocument(string $jurisdiction, string $documentSlug, string $langCode): array {
        $content = $this->getDocument($jurisdiction, $documentSlug, $langCode);
        if(empty($content)) return ['missing' => [], 'warnings' => ['Document not found'], 'score' => 0];

        $body = preg_replace('/^---\n.*?\n---\n/s', '', $content);

        $required = $this->getRequiredSections($documentSlug, $jurisdiction);
        $missing  = [];
        $found    = 0;
        $warnings = [];

        foreach($required as $section => $keywords) {
            $detected = false;
            foreach($keywords as $keyword) {
                if(stripos($body, $keyword) !== false) {
                    $detected = true;
                    break;
                }
            }
            if($detected) {
                $found++;
            } else {
                $missing[] = $section;
            }
        }

        $wordCount = str_word_count(strip_tags($body));
        if($wordCount < 300) $warnings[] = "Document seems too short ({$wordCount} words). Consider regenerating.";
        if(preg_match('/\[YOUR [A-Z]+\]|\[INSERT|\[PLACEHOLDER/i', $body)) $warnings[] = "Document contains unfilled placeholders.";
        if(!preg_match('/last updated|effective date/i', $body)) $warnings[] = "No 'Last Updated' date found.";

        $total = count($required);
        $score = $total > 0 ? round(($found / $total) * 100) : 100;

        return [
            'missing'    => $missing,
            'warnings'   => $warnings,
            'score'      => $score,
            'found'      => $found,
            'total'      => $total,
            'word_count' => $wordCount,
        ];
    }

    public function hasAI(): bool {
        $ai = $this->getAI();
        return $ai !== null && $ai->isEnabled();
    }

    // =========================================================================
    // Prompt Builder
    // =========================================================================

    protected function buildPrompt(string $jurisdiction, string $documentSlug, string $langCode): string {
        $jurisdictions = ProcessLegalDocsConfig::getJurisdictions();
        $requirements  = ProcessLegalDocsConfig::getJurisdictionRequirements();
        $languages     = ProcessLegalDocsConfig::getLanguages();
        $docTypes      = ProcessLegalDocsConfig::getDocumentTypes();

        $jurName  = $jurisdictions[$jurisdiction]['name'] ?? $jurisdiction;
        $langName = $languages[$langCode] ?? $langCode;
        $docLabel = $docTypes[$documentSlug]['label'] ?? $documentSlug;
        $lawInfo  = $requirements[$jurisdiction] ?? ['law' => $jurisdiction, 'requirements' => []];
        $today    = date('Y-m-d');
        $year     = date('Y');

        $ownerType = $this->config['owner_type'] ?? 'company';
        if($ownerType === 'individual') {
            $ownerName   = trim(($this->config['owner_first_name'] ?? '') . ' ' . ($this->config['owner_last_name'] ?? ''));
            $ownerEntity = 'individual/sole trader';
        } else {
            $ownerName   = $this->config['owner_company_name'] ?? '';
            $ownerEntity = 'company';
        }
        $regNum       = $this->config['owner_reg_number'] ?? '';
        $ownerCountry = $this->config['owner_country'] ?? '';
        $ownerAddress = $this->config['owner_address'] ?? '';
        $ownerEmail   = $this->config['owner_email'] ?? '';
        $websiteUrl   = rtrim($this->config['owner_website'] ?? wire('config')->httpHost, '/');
        $dpoName      = $this->config['dpo_name'] ?? '';
        $dpoEmail     = $this->config['dpo_email'] ?? '';

        // ── System role ───────────────────────────────────────────────────────
        $systemRole  = "You are a senior legal counsel and data protection expert with 20+ years of experience ";
        $systemRole .= "drafting privacy policies, terms of service, and compliance documents for technology companies worldwide.\n\n";
        $systemRole .= "You specialize in:\n";
        $systemRole .= "- GDPR, UK GDPR, CCPA/CPRA, PIPEDA, LGPD, APPI, PIPL, and all major global data protection frameworks\n";
        $systemRole .= "- SaaS, e-commerce, marketplace, and content platforms\n";
        $systemRole .= "- Cross-border data transfer mechanisms (SCCs, adequacy decisions, BCRs)\n";
        $systemRole .= "- Plain-language legal drafting that is both legally precise and user-readable\n\n";
        $systemRole .= "Your documents are used by real businesses and reviewed by lawyers. ";
        $systemRole .= "Every clause must be legally accurate, jurisdiction-specific, and directly relevant to the actual business described.";

        // ── Owner / site context ──────────────────────────────────────────────
        $cd = $this->contextData;

        $siteContext  = "Website: {$websiteUrl}\n";
        $siteContext .= "Owner: {$ownerName} ({$ownerEntity})";
        if($regNum) $siteContext .= ", Reg. No. {$regNum}";
        $siteContext .= "\nRegistered in: {$ownerCountry}\nAddress: {$ownerAddress}\nContact: {$ownerEmail}\n";
        if($dpoName) {
            $siteContext .= "DPO: {$dpoName}";
            if($dpoEmail) $siteContext .= " <{$dpoEmail}>";
            $siteContext .= "\n";
        }

        $businessDetails = [
            'Business description' => $this->config['business_description'] ?? '',
            'Target markets' => $this->config['target_markets'] ?? '',
            'Customer type' => $this->formatCustomerType($this->config['customer_type'] ?? ''),
            'Serves children/minors' => !empty($this->config['serves_children']) ? 'Yes' : '',
            'Minimum age' => $this->config['minimum_age'] ?? '',
            'Data categories collected' => $this->config['data_categories'] ?? '',
            'Sensitive data' => $this->config['sensitive_data_details'] ?? '',
            'Data retention' => $this->config['retention_summary'] ?? '',
            'Processors/sub-processors' => $this->joinPresetAndCustom($this->config['processor_presets'] ?? [], $this->config['processors'] ?? '', 'processors'),
            'Analytics providers' => $this->joinPresetAndCustom($this->config['analytics_presets'] ?? [], $this->config['analytics_providers'] ?? '', 'analytics'),
            'Payment providers' => $this->joinPresetAndCustom($this->config['payment_presets'] ?? [], $this->config['payment_providers'] ?? '', 'payments'),
            'Email/marketing provider' => $this->joinPresetAndCustom($this->config['email_marketing_presets'] ?? [], $this->config['email_marketing_provider'] ?? '', 'email'),
            'Cookie consent tool' => $this->joinPresetAndCustom($this->config['cookie_consent_preset'] ?? '', $this->config['cookie_consent_tool'] ?? '', 'cookies'),
            'Refund policy' => $this->config['refund_policy_summary'] ?? '',
            'Subscription terms' => $this->config['subscription_terms'] ?? '',
        ];

        $hasBusinessDetails = false;
        foreach($businessDetails as $value) {
            if(trim((string) $value) !== '') {
                $hasBusinessDetails = true;
                break;
            }
        }

        if($hasBusinessDetails) {
            $siteContext .= "\n### Business & Compliance Details (provided by site owner)\n";
            foreach($businessDetails as $label => $value) {
                $value = trim((string) $value);
                if($value === '') continue;
                $siteContext .= "{$label}: {$value}\n";
            }
        }

        if(!empty($cd)) {
            $siteContext .= "\n### Site Technical Profile (auto-detected)\n";
            if(!empty($cd['site_name']))   $siteContext .= "Domain: {$cd['site_name']}\n";
            if(!empty($cd['timezone']))    $siteContext .= "Timezone: {$cd['timezone']}\n";
            if(!empty($cd['total_pages'])) $siteContext .= "Total pages: {$cd['total_pages']}\n";
            if(!empty($cd['site_sections'])) {
                $siteContext .= "Main site sections: " . implode(', ', array_slice($cd['site_sections'], 0, 15)) . "\n";
            }
            if(!empty($cd['templates_with_pages'])) {
                $siteContext .= "Active content types: " . implode(', ', array_slice($cd['templates_with_pages'], 0, 12)) . "\n";
            } elseif(!empty($cd['templates'])) {
                $siteContext .= "Content templates: " . implode(', ', array_slice($cd['templates'], 0, 12)) . "\n";
            }

            if(!empty($cd['features'])) {
                $siteContext .= "\n### Features That Affect This Document\n";
                foreach($cd['features'] as $feature) {
                    $siteContext .= "- {$feature}\n";
                }
            }

            $flags = [];
            if(!empty($cd['has_ecommerce']))    $flags[] = "E-COMMERCE: include payment data, order records, transaction history clauses";
            if(!empty($cd['has_auth']))          $flags[] = "USER ACCOUNTS: include account creation, login sessions, account deletion clauses";
            if(!empty($cd['has_forms']))         $flags[] = "FORMS: include form submission data collection and storage clauses";
            if(!empty($cd['has_newsletter']))    $flags[] = "NEWSLETTER: include email subscription, marketing communications, unsubscribe clauses";
            if(!empty($cd['has_multilanguage'])) $flags[] = "MULTI-LANGUAGE: reference language-specific legal obligations";
            if(!empty($cd['has_api']))           $flags[] = "API: include developer/third-party API access data clauses";
            if(!empty($cd['has_cron']))          $flags[] = "SCHEDULED TASKS: include automated background processing clauses";
            if(!empty($cd['has_sessions']))      $flags[] = "DATABASE SESSIONS: include session data storage and retention clauses";
            if(!empty($cd['file_fields']))       $flags[] = "FILE UPLOADS: include user-uploaded file storage, retention, deletion clauses";
            if(!empty($cd['image_fields']))      $flags[] = "IMAGE UPLOADS: include user photo/image handling and privacy clauses";
            if(!empty($cd['payment_fields']))    $flags[] = "PAYMENT DATA: include payment card handling, PCI-DSS considerations";

            if(!empty($flags)) {
                $siteContext .= "\n### MANDATORY CLAUSE TRIGGERS\n";
                foreach($flags as $flag) {
                    $siteContext .= "MUST INCLUDE — {$flag}\n";
                }
            }

            if(!empty($cd['personal_data_fields'])) {
                $siteContext .= "\n### Personal Data Collected (detected from site fields)\n";
                foreach($cd['personal_data_fields'] as $description) {
                    $siteContext .= "- {$description}\n";
                }
            }

            if(!empty($cd['route_features'])) {
                foreach($cd['route_features'] as $rf) {
                    $siteContext .= "- {$rf} (from URL analysis)\n";
                }
            }
            if(!empty($cd['key_urls'])) {
                $siteContext .= "Key URLs detected: " . implode(', ', array_slice($cd['key_urls'], 0, 10)) . "\n";
            }
            if(!empty($cd['business_context'])) {
                $siteContext .= "\n### Real Site Content (sample pages)\n";
                $siteContext .= $cd['business_context'] . "\n";
            }
            if(!empty($cd['sample_descriptions'])) {
                $siteContext .= "Content excerpts:\n";
                foreach(array_slice($cd['sample_descriptions'], 0, 3) as $desc) {
                    $siteContext .= "  — " . $desc . "\n";
                }
            }
            if(!empty($cd['relevant_modules'])) {
                $siteContext .= "Data-relevant modules: " . implode(', ', $cd['relevant_modules']) . "\n";
            }
            if(!empty($cd['exported_at'])) {
                $siteContext .= "Site data snapshot: {$cd['exported_at']}\n";
            }
        }

        // ── Legal framework ───────────────────────────────────────────────────
        $legalFramework  = "Governing law: {$lawInfo['law']}\n";
        $legalFramework .= "Jurisdiction: {$jurName}\n";
        $legalFramework .= "Required legal provisions:\n";
        foreach($lawInfo['requirements'] as $req) {
            $legalFramework .= "  * {$req}\n";
        }

        // ── Document-specific instructions ────────────────────────────────────
        $docInstructions = $this->getDocumentInstructions($documentSlug, $jurisdiction, $jurName, $langName);

        // ── Formatting rules ──────────────────────────────────────────────────
        $formatRules  = "CRITICAL FORMATTING AND QUALITY RULES:\n\n";
        $formatRules .= "1. LANGUAGE: Write the entire document in {$langName}. All headings, body text, legal terms must be in {$langName}.\n\n";
        $formatRules .= "2. NO PLACEHOLDERS: Never use [COMPANY NAME], [INSERT DATE], [YOUR ADDRESS]. Use actual data provided. If info is missing, omit that clause.\n\n";
        $formatRules .= "3. REAL LEGAL CONTENT: Every clause must contain substantive legal text. No vague filler.\n\n";
        $formatRules .= "4. JURISDICTION ACCURACY: Include all legally required sections for {$jurName}. Reference the correct supervisory authority and legal terminology.\n\n";
        $formatRules .= "5. SITE-SPECIFIC: Tailor every section to the actual website described. Only include sections for features the site actually has.\n\n";
        $formatRules .= "6. STRUCTURE: Use ## for main sections, ### for subsections. Number all main sections. Include a table of contents if document exceeds 8 sections.\n\n";
        $formatRules .= "7. DATES: Use \"Last Updated: {$today}\" and \"Effective Date: {$today}\" at the top. Copyright: © {$year} {$ownerName}.\n\n";
        $formatRules .= "8. OUTPUT: Output ONLY the Markdown document. No preamble, no explanation, no code fences. Start directly with the document title.";

        // ── Custom user instructions ──────────────────────────────────────────
        $customInstructions = '';
        $customKey = 'custom_prompt_' . $documentSlug;
        if(!empty($this->config[$customKey])) {
            $customInstructions  = "\n\n## ADDITIONAL INSTRUCTIONS FROM SITE OWNER\n";
            $customInstructions .= "The following instructions MUST be followed:\n";
            $customInstructions .= $this->config[$customKey];
        } elseif(!empty($this->config['custom_prompt_global'])) {
            $customInstructions  = "\n\n## ADDITIONAL INSTRUCTIONS FROM SITE OWNER\n";
            $customInstructions .= $this->config['custom_prompt_global'];
        }

        // ── Assemble ──────────────────────────────────────────────────────────
        $prompt  = $systemRole . "\n\n---\n\n";
        $prompt .= "## YOUR TASK\n\n";
        $prompt .= "Draft a complete, legally binding {$docLabel} for the following business:\n\n";
        $prompt .= $siteContext . "\n";
        $prompt .= "## LEGAL FRAMEWORK\n\n" . $legalFramework . "\n";
        $prompt .= "## DOCUMENT-SPECIFIC REQUIREMENTS\n\n" . $docInstructions . "\n";
        $prompt .= "## FORMATTING AND QUALITY RULES\n\n" . $formatRules;
        if($customInstructions) $prompt .= $customInstructions;

        return $prompt;
    }

    protected function getDocumentInstructions(string $slug, string $jurisdiction, string $jurName, string $langName): string {
        switch($slug) {

            case 'privacy-policy':
                $t  = "Draft a comprehensive Privacy Policy. Required sections:\n\n";
                $t .= "1. Introduction & Scope — who this policy applies to, effective date\n";
                $t .= "2. Data Controller Identity — legal name, address, registration, contact, DPO if applicable\n";
                $t .= "3. What Personal Data We Collect — organized by category:\n";
                $t .= "   a) Data you provide (registration, forms, purchases, communications)\n";
                $t .= "   b) Data collected automatically (IP, cookies, device info, usage analytics)\n";
                $t .= "   c) Data from third parties (social login, payment processors, analytics)\n";
                $t .= "4. Legal Basis for Processing — for each data category, state the specific legal basis under {$jurName} law\n";
                $t .= "5. Purposes of Processing — for each purpose, link it to the legal basis and data categories used\n";
                $t .= "6. Data Retention — concrete retention periods for each data category (e.g. '3 years from last interaction', not 'as long as necessary')\n";
                $t .= "7. International Data Transfers — mechanisms used (SCCs, adequacy decisions, etc.) if applicable\n";
                $t .= "8. Third-Party Sharing — categories of recipients, their role (processor vs controller), safeguards\n";
                $t .= "9. Cookies & Tracking — types, purpose, how to manage/opt-out\n";
                $t .= "10. Your Rights — every applicable right under {$jurName} law with specific instructions and response timeframes\n";
                $t .= "11. Children's Privacy — age threshold, parental consent requirements\n";
                $t .= "12. Security Measures — specific technical and organizational measures\n";
                $t .= "13. Changes to This Policy — how users will be notified\n";
                $t .= "14. Contact / Lodge a Complaint — full contact details, supervisory authority name and contact\n";
                return $t;

            case 'cookie-policy':
                $t  = "Draft a detailed Cookie Policy. Required sections:\n\n";
                $t .= "1. What Are Cookies — clear explanation for non-technical users\n";
                $t .= "2. Why We Use Cookies — specific purposes linked to specific cookies\n";
                $t .= "3. Cookie Inventory Table — for each category: | Cookie Name | Provider | Purpose | Type | Duration | Legal Basis |\n";
                $t .= "   Include: strictly necessary, functional, analytics, marketing/tracking cookies\n";
                $t .= "4. Third-Party Cookies — list specific providers (Google Analytics, Facebook Pixel, etc.) with links to their privacy policies\n";
                $t .= "5. Cookie Consent — how consent is obtained, recorded, and what 'strictly necessary' cookies are exempt\n";
                $t .= "6. How to Manage Cookies — browser-by-browser instructions (Chrome, Firefox, Safari, Edge), opt-out links\n";
                $t .= "7. Do Not Track (DNT) — whether the site honors DNT signals\n";
                $t .= "8. Impact of Disabling Cookies — what functionality breaks\n";
                $t .= "9. Updates to This Policy\n";
                return $t;

            case 'terms-of-use':
                $t  = "Draft comprehensive Terms of Use. Required sections:\n\n";
                $t .= "1. Agreement to Terms — how users accept, what constitutes acceptance\n";
                $t .= "2. Eligibility — minimum age, geographic restrictions, account requirements\n";
                $t .= "3. Account Registration & Security — obligations, password security, suspension/termination\n";
                $t .= "4. Description of Services — what the website provides, key features, limitations\n";
                $t .= "5. Acceptable Use Policy — detailed list of prohibited conduct (illegal use, scraping, IP infringement, spam, etc.)\n";
                $t .= "6. Intellectual Property — ownership, licenses granted to users, user-generated content license\n";
                $t .= "7. User Content — submission rules, content standards, moderation, DMCA procedure if applicable\n";
                $t .= "8. Payment Terms — pricing, billing, refunds, failed payments (include only if site has payments)\n";
                $t .= "9. Third-Party Links & Services — disclaimer for third-party content\n";
                $t .= "10. Disclaimers & Warranties — 'as-is' disclaimer, uptime disclaimer\n";
                $t .= "11. Limitation of Liability — liability cap, excluded damages, jurisdictional carve-outs under {$jurName} law\n";
                $t .= "12. Indemnification — user indemnification obligations\n";
                $t .= "13. Governing Law & Dispute Resolution — specific court/arbitration venue, class action waiver if applicable\n";
                $t .= "14. Termination — conditions, effects, survival of clauses\n";
                $t .= "15. Changes to Terms — notice period and method\n";
                $t .= "16. Contact Information\n";
                return $t;

            case 'data-processing-agreement':
                $t  = "Draft a Data Processing Agreement (DPA) compliant with {$jurName}. Required sections:\n\n";
                $t .= "1. Definitions — Controller, Processor, Sub-processor, Personal Data, Processing (using exact {$jurName} statutory definitions)\n";
                $t .= "2. Subject Matter & Duration\n";
                $t .= "3. Nature and Purpose of Processing\n";
                $t .= "4. Type of Personal Data & Categories of Data Subjects\n";
                $t .= "5. Controller Obligations — documented instructions, lawfulness\n";
                $t .= "6. Processor Obligations — confidentiality, security, sub-processors, data subject rights assistance, breach notification, deletion/return, audit rights\n";
                $t .= "7. Security Measures — specific technical and organizational measures (Annex)\n";
                $t .= "8. Sub-processors — approval mechanism, flow-down requirements\n";
                $t .= "9. Data Subject Rights — assistance obligations\n";
                $t .= "10. Personal Data Breach — 72-hour notification timeline\n";
                $t .= "11. Deletion or Return of Data — post-termination obligations\n";
                $t .= "12. Audit Rights\n";
                $t .= "13. International Transfers\n";
                $t .= "14. Governing Law\n";
                $t .= "Include Annex I (Processing Details) and Annex II (Security Measures) templates.\n";
                return $t;

            case 'ccpa-notice':
                $t  = "Draft a CCPA/CPRA Notice at Collection compliant with California law. Required sections:\n\n";
                $t .= "1. Categories of Personal Information — use exact CCPA statutory categories with purpose and retention period for each\n";
                $t .= "2. Purposes for Collection and Use\n";
                $t .= "3. Sale or Sharing of Personal Information — explicit statement; if yes, opt-out mechanism\n";
                $t .= "4. Sensitive Personal Information — whether collected; opt-out rights\n";
                $t .= "5. Your California Privacy Rights — Right to Know, Delete, Correct, Opt-Out, Limit SPI, Non-Discrimination\n";
                $t .= "   For each right: how to submit, verification process, 45-day response timeline\n";
                $t .= "6. Authorized Agent — how to submit requests via agent\n";
                $t .= "7. How to Submit Requests — URL, email, toll-free number\n";
                $t .= "8. Contact — last reviewed date\n";
                $t .= "Use precise CCPA/CPRA statutory language and cite Cal. Civ. Code sections where appropriate.\n";
                return $t;

            case 'refund-policy':
                $t  = "Draft a clear Refund and Returns Policy. Required sections:\n\n";
                $t .= "1. Scope — what products/services this covers\n";
                $t .= "2. Eligibility — conditions, time windows (e.g. 30 days from purchase)\n";
                $t .= "3. Non-Refundable Items — explicit exclusions (digital downloads, custom work, etc.)\n";
                $t .= "4. Refund Process — step-by-step instructions, required information, contact\n";
                $t .= "5. Processing Time — how long, how issued (original payment method, store credit)\n";
                $t .= "6. Partial Refunds — conditions\n";
                $t .= "7. Defective or Incorrect Items — separate process, consumer rights under {$jurName} law\n";
                $t .= "8. Chargebacks — policy, consequences of fraudulent chargebacks\n";
                $t .= "9. Consumer Rights — statutory rights under {$jurName} law that cannot be contracted out of\n";
                $t .= "10. Contact Information\n";
                return $t;

            case 'disclaimer':
                $t  = "Draft a comprehensive Website Disclaimer. Required sections:\n\n";
                $t .= "1. General Disclaimer — no warranty of accuracy, completeness, or timeliness\n";
                $t .= "2. Not Professional Advice — not legal, financial, medical or other professional advice; recommend qualified professionals\n";
                $t .= "3. External Links — no endorsement or responsibility for third-party content\n";
                $t .= "4. No Liability for Errors — limitation for errors, omissions, or inaccuracies\n";
                $t .= "5. No Liability for Losses — disclaimer for losses arising from reliance on website content\n";
                $t .= "6. Availability — no guarantee of uptime or error-free operation\n";
                $t .= "7. Intellectual Property Notice — copyright, trademark, restricted use\n";
                $t .= "8. User-Generated Content — disclaimer if applicable\n";
                $t .= "9. Jurisdiction-Specific Limitations — liability limitations may not apply in EU, AU, NZ\n";
                $t .= "10. Changes — right to update without notice\n";
                $t .= "11. Acceptance — use of the site constitutes acceptance\n";
                $t .= "Calibrate limitation clauses to be enforceable under {$jurName} law.\n";
                return $t;

            default:
                return "Draft a complete, professional " . $slug . " document tailored to the business described above and compliant with {$jurName} law. Include all sections required by law and relevant to the actual services provided. Be specific, concrete, and legally precise.";
        }
    }

    protected function formatCustomerType(string $type): string {
        switch($type) {
            case 'b2c':
                return 'B2C / consumers';
            case 'b2b':
                return 'B2B / businesses';
            case 'both':
                return 'Both B2C and B2B';
            default:
                return '';
        }
    }

    protected function joinPresetAndCustom($selected, string $custom, string $type): string {
        $labels = [];
        $options = $this->getServicePresetOptions($type);

        if(!is_array($selected)) $selected = $selected ? [$selected] : [];
        foreach($selected as $value) {
            if(isset($options[$value])) $labels[] = $options[$value];
        }

        $custom = trim($custom);
        if($custom !== '') $labels[] = $custom;

        $labels = array_values(array_unique(array_filter($labels)));
        return implode(', ', $labels);
    }

    protected function getServicePresetOptions(string $type): array {
        $options = [
            'processors' => [
                'cloudflare' => 'Cloudflare',
                'aws' => 'Amazon Web Services',
                'google_cloud' => 'Google Cloud',
                'microsoft_azure' => 'Microsoft Azure',
                'digitalocean' => 'DigitalOcean',
                'hetzner' => 'Hetzner',
                'github' => 'GitHub',
                'hubspot' => 'HubSpot',
                'zendesk' => 'Zendesk',
                'intercom' => 'Intercom',
                'openai' => 'OpenAI',
            ],
            'analytics' => [
                'google_analytics' => 'Google Analytics',
                'google_tag_manager' => 'Google Tag Manager',
                'matomo' => 'Matomo',
                'plausible' => 'Plausible',
                'fathom' => 'Fathom Analytics',
                'meta_pixel' => 'Meta Pixel',
                'hotjar' => 'Hotjar',
            ],
            'payments' => [
                'stripe' => 'Stripe',
                'paypal' => 'PayPal',
                'square' => 'Square',
                'adyen' => 'Adyen',
                'razorpay' => 'Razorpay',
                'mollie' => 'Mollie',
                'wise' => 'Wise',
            ],
            'email' => [
                'mailchimp' => 'Mailchimp',
                'brevo' => 'Brevo',
                'klaviyo' => 'Klaviyo',
                'sendgrid' => 'SendGrid',
                'mailgun' => 'Mailgun',
                'postmark' => 'Postmark',
                'hubspot_marketing' => 'HubSpot Marketing',
            ],
            'cookies' => [
                'cookiebot' => 'Cookiebot',
                'onetrust' => 'OneTrust',
                'klaro' => 'Klaro',
                'termly' => 'Termly',
                'iubenda' => 'Iubenda',
                'custom_banner' => 'Custom cookie banner',
                'none' => 'No cookie consent tool',
            ],
        ];

        return $options[$type] ?? [];
    }

    // =========================================================================
    // File I/O
    // =========================================================================

    protected function saveDocument(string $jurisdiction, string $documentSlug, string $langCode, string $markdown): bool {
        $dir  = $this->basePath . '/' . $jurisdiction;
        $path = $this->getDocumentPath($jurisdiction, $documentSlug, $langCode);

        if(!is_dir($dir)) {
            if(!mkdir($dir, 0755, true)) return false;
        }

        $htaccess = $this->basePath . '/.htaccess';
        if(!file_exists($htaccess)) {
            file_put_contents($htaccess, "Deny from all\n");
        }

        $ownerType = $this->config['owner_type'] ?? 'company';
        if($ownerType === 'individual') {
            $ownerName = trim(($this->config['owner_first_name'] ?? '') . ' ' . ($this->config['owner_last_name'] ?? ''));
        } else {
            $ownerName = $this->config['owner_company_name'] ?? '';
        }

        $docTypes  = ProcessLegalDocsConfig::getDocumentTypes();
        $languages = ProcessLegalDocsConfig::getLanguages();
        $jurInfo   = ProcessLegalDocsConfig::getJurisdictions();

        $title    = $docTypes[$documentSlug]['label'] ?? $documentSlug;
        $jurName  = $jurInfo[$jurisdiction]['name'] ?? $jurisdiction;
        $langName = $languages[$langCode] ?? $langCode;
        $website  = $this->config['owner_website'] ?? wire('config')->httpHost;

        $frontmatter  = "---\n";
        $frontmatter .= "title: \"{$title}\"\n";
        $frontmatter .= "jurisdiction: {$jurisdiction}\n";
        $frontmatter .= "jurisdiction_name: \"{$jurName}\"\n";
        $frontmatter .= "language: {$langCode}\n";
        $frontmatter .= "language_name: \"{$langName}\"\n";
        $frontmatter .= "generated: " . date('Y-m-d') . "\n";
        $frontmatter .= "review_status: " . ($this->config['default_review_status'] ?? 'draft') . "\n";
        if(!empty($this->config['reviewer_name'])) {
            $frontmatter .= "reviewer: \"" . $this->escapeYaml((string) $this->config['reviewer_name']) . "\"\n";
        }
        $frontmatter .= "last_reviewed: \n";
        $frontmatter .= "owner: \"{$ownerName}\"\n";
        $frontmatter .= "website: \"{$website}\"\n";
        $frontmatter .= "generator: ProcessLegalDocs for ProcessWire\n";
        $frontmatter .= "---\n\n";

        $disclaimer = self::DISCLAIMER . "\n\n---\n\n";
        $final = $frontmatter . $disclaimer . $markdown;

        if(file_put_contents($path, $final) === false) return false;

        try {
            $this->syncDocumentPage($jurisdiction, $documentSlug, $langCode, $final, $title, $jurName, $langName);
        } catch(\Throwable $e) {
            // Page publishing is optional; keep Markdown generation successful if sync fails.
        }

        return true;
    }

    protected function escapeYaml(string $value): string {
        return str_replace('"', '\"', $value);
    }

    protected function syncDocumentPage(string $jurisdiction, string $documentSlug, string $langCode, string $content, string $title, string $jurName, string $langName): void {
        if(empty($this->config['publish_to_pages'])) return;

        $parentPath = trim((string) ($this->config['publish_parent_path'] ?? ''));
        $templateName = trim((string) ($this->config['publish_template'] ?? ''));
        $bodyField = trim((string) ($this->config['publish_body_field'] ?? 'body'));

        if($parentPath === '' || $templateName === '' || $bodyField === '') return;

        $pages = wire('pages');
        $templates = wire('templates');
        $fields = wire('fields');
        $sanitizer = wire('sanitizer');

        $parent = $pages->get($parentPath);
        $template = $templates->get($templateName);
        $field = $fields->get($bodyField);

        if(!$parent || !$parent->id || !$template || !$field) return;

        $name = $sanitizer->pageName($jurisdiction . '-' . $documentSlug . '-' . $langCode, true);
        $page = $parent->child("name={$name}, include=all");
        if(!$page || !$page->id) {
            $page = new Page();
            $page->template = $template;
            $page->parent = $parent;
            $page->name = $name;
        }

        $page->title = $title . ' — ' . $jurName . ' (' . $langName . ')';
        $page->set($bodyField, $content);

        if(($this->config['publish_status'] ?? 'unpublished') === 'published') {
            $page->removeStatus(Page::statusUnpublished);
        } else {
            $page->addStatus(Page::statusUnpublished);
        }

        $page->of(false);
        $page->save();
    }

    // =========================================================================
    // Context Integration
    // =========================================================================

    protected function loadContextData(): void {
        $context = wire('modules')->getModule('Context', ['noInit' => true]);
        if(!$context) {
            $this->contextData = $this->detectFromLiveAPI();
            return;
        }

        $exportPath = method_exists($context, 'getContextPath') ? $context->getContextPath() : '';
        if(!$exportPath || !is_dir($exportPath)) {
            $this->contextData = $this->detectFromLiveAPI();
            return;
        }

        // Config
        $configData = $this->readJsonFile($exportPath . 'config.json');
        if($configData) {
            $this->contextData['site_name']   = $configData['site_name'] ?? '';
            $this->contextData['pw_version']  = $configData['pw_version'] ?? '';
            $this->contextData['timezone']    = $configData['timezone'] ?? '';
            $this->contextData['exported_at'] = $configData['exported_at'] ?? '';
        }

        // Templates
        $templates = $this->readJsonFile($exportPath . 'templates.json');
        if($templates) {
            $this->contextData = array_merge($this->contextData, $this->analyzeTemplates($templates));
        }

        // Modules
        $modules = $this->readJsonFile($exportPath . 'modules.json');
        if($modules) {
            $this->contextData = array_merge($this->contextData, $this->analyzeModules($modules));
        }

        // Structure
        $structure = $this->readJsonFile($exportPath . 'structure.json');
        if($structure) {
            $this->contextData = array_merge($this->contextData, $this->analyzeStructure($structure));
        }

        // Field definitions
        $fieldDefs = $this->readJsonFile($exportPath . 'metadata/field-definitions.json');
        if($fieldDefs) {
            $this->contextData = array_merge($this->contextData, $this->analyzeFieldDefinitions($fieldDefs));
        }

        // Routes
        $routes = $this->readJsonFile($exportPath . 'metadata/routes.json');
        if($routes) {
            $this->contextData = array_merge($this->contextData, $this->analyzeRoutes($routes));
        }

        // Samples
        $samplesAll = $this->readJsonFile($exportPath . 'samples/_all-samples.json');
        if($samplesAll) {
            $this->contextData = array_merge($this->contextData, $this->analyzeSamples($samplesAll));
        }

        // Supplement with live API
        $liveData = $this->detectFromLiveAPI();
        foreach($liveData as $k => $v) {
            if(empty($this->contextData[$k])) $this->contextData[$k] = $v;
        }
    }

    protected function readJsonFile(string $path): ?array {
        if(!file_exists($path)) return null;
        $data = json_decode(file_get_contents($path), true);
        return is_array($data) ? $data : null;
    }

    protected function analyzeTemplates(array $templates): array {
        $result = [
            'templates'            => [],
            'personal_data_fields' => [],
            'file_fields'          => [],
            'image_fields'         => [],
            'payment_fields'       => [],
            'all_field_names'      => [],
            'templates_with_pages' => [],
        ];

        $personalIndicators = [
            'email' => 'email address', 'phone' => 'phone number', 'mobile' => 'mobile number',
            'firstname' => 'first name', 'lastname' => 'last name', 'fullname' => 'full name',
            'name' => 'name', 'address' => 'postal address', 'street' => 'street address',
            'city' => 'city', 'zip' => 'ZIP/postal code', 'postal' => 'postal code',
            'country' => 'country', 'birth' => 'date of birth', 'dob' => 'date of birth',
            'gender' => 'gender', 'avatar' => 'profile photo', 'photo' => 'photo',
            'ip' => 'IP address', 'location' => 'geolocation', 'gps' => 'GPS coordinates',
            'card' => 'payment card data', 'payment' => 'payment information',
            'billing' => 'billing information', 'ssn' => 'social security number',
            'passport' => 'passport number', 'tax' => 'tax identification',
            'username' => 'username', 'password' => 'password',
            'newsletter' => 'newsletter subscription', 'subscribe' => 'subscription data',
            'company' => 'company name', 'vat' => 'VAT number',
        ];

        foreach($templates as $tpl) {
            $name      = $tpl['name'] ?? '';
            $pageCount = $tpl['pageCount'] ?? 0;

            $result['templates'][] = $name . ($pageCount ? " ({$pageCount} pages)" : '');
            if($pageCount > 0) $result['templates_with_pages'][] = $name;

            foreach($tpl['fields'] ?? [] as $field) {
                $fieldName  = strtolower($field['name'] ?? '');
                $fieldType  = $field['type'] ?? '';
                $fieldLabel = strtolower($field['label'] ?? '');
                $combined   = $fieldName . ' ' . $fieldLabel;

                $result['all_field_names'][] = $field['name'];

                foreach($personalIndicators as $keyword => $description) {
                    if(strpos($combined, $keyword) !== false) {
                        $result['personal_data_fields'][$keyword] = $description;
                    }
                }

                if(strpos($fieldType, 'File') !== false)  $result['file_fields'][]  = $field['name'];
                if(strpos($fieldType, 'Image') !== false) $result['image_fields'][] = $field['name'];
                if(preg_match('/payment|card|price|amount|checkout|order|invoice/i', $combined)) {
                    $result['payment_fields'][] = $field['name'];
                }
            }
        }

        $result['personal_data_fields'] = array_values(array_unique($result['personal_data_fields']));
        $result['file_fields']          = array_unique($result['file_fields']);
        $result['image_fields']         = array_unique($result['image_fields']);
        $result['all_field_names']      = array_unique($result['all_field_names']);

        return $result;
    }

    protected function analyzeModules(array $modules): array {
        $result = [
            'features'          => [],
            'relevant_modules'  => [],
            'has_ecommerce'     => false,
            'has_auth'          => false,
            'has_forms'         => false,
            'has_multilanguage' => false,
            'has_api'           => false,
            'has_cron'          => false,
            'has_sessions'      => false,
            'has_newsletter'    => false,
        ];

        $moduleMap = [
            'Padloper'              => ['e-commerce / online store',                    'has_ecommerce'],
            'PadOrders'             => ['online order processing',                      'has_ecommerce'],
            'LoginRegister'         => ['user registration and login',                  'has_auth'],
            'LoginRegisterPro'      => ['advanced user registration',                   'has_auth'],
            'ProcessLogin'          => ['user authentication',                          'has_auth'],
            'FormBuilder'           => ['contact and data collection forms',            'has_forms'],
            'Subscribe'             => ['newsletter subscription',                      'has_newsletter'],
            'LanguageSupport'       => ['multi-language content',                       'has_multilanguage'],
            'ProcessRestApi'        => ['REST API',                                     'has_api'],
            'GraphQL'               => ['GraphQL API',                                  'has_api'],
            'SessionHandlerDB'      => ['database session storage',                     'has_sessions'],
            'LazyCron'              => ['scheduled background tasks',                   'has_cron'],
            'CommentNotifications'  => ['user comments',                                null],
            'PlausibleAnalytics'    => ['analytics tracking (Plausible)',               null],
            'GoogleAnalytics'       => ['analytics tracking (Google Analytics)',        null],
        ];

        $moduleNames = array_column($modules, 'name');

        foreach($moduleMap as $moduleName => $config) {
            if(in_array($moduleName, $moduleNames)) {
                list($feature, $flag) = $config;
                if(!in_array($feature, $result['features'])) $result['features'][] = $feature;
                if($flag) $result[$flag] = true;
                $result['relevant_modules'][] = $moduleName;
            }
        }

        if(!in_array('analytics and tracking', $result['features'])) {
            $result['features'][] = 'analytics and tracking';
        }

        return $result;
    }

    protected function analyzeStructure(array $structure): array {
        $count    = 0;
        $sections = [];
        $this->countPages($structure, $count, $sections, 0);
        return [
            'total_pages'   => $count,
            'site_sections' => array_unique($sections),
        ];
    }

    protected function countPages(array $node, int &$count, array &$sections, int $depth): void {
        foreach($node as $item) {
            if(!is_array($item)) continue;
            if(isset($item['name'])) {
                $count++;
                if($depth === 1 && !empty($item['name'])) $sections[] = $item['name'];
            }
            if(!empty($item['children'])) {
                $this->countPages($item['children'], $count, $sections, $depth + 1);
            }
        }
    }

    protected function analyzeFieldDefinitions(array $fieldDefs): array {
        $typeCounts = [];
        foreach($fieldDefs as $field) {
            $type = $field['type'] ?? 'unknown';
            $typeCounts[$type] = ($typeCounts[$type] ?? 0) + 1;
        }
        arsort($typeCounts);
        $summary = [];
        foreach(array_slice($typeCounts, 0, 10, true) as $type => $count) {
            $summary[] = "{$type} ({$count})";
        }
        return ['field_types_summary' => $summary];
    }

    protected function analyzeRoutes(array $routes): array {
        $result = [
            'has_shop_url'    => false,
            'has_account_url' => false,
            'has_api_url'     => false,
            'has_blog_url'    => false,
            'has_login_url'   => false,
            'key_urls'        => [],
            'route_features'  => [],
        ];

        $patterns = [
            'has_shop_url'    => ['/shop', '/store', '/products', '/cart', '/checkout', '/order'],
            'has_account_url' => ['/account', '/profile', '/dashboard', '/my-'],
            'has_api_url'     => ['/api/', '/v1/', '/v2/', '/graphql'],
            'has_blog_url'    => ['/blog', '/news', '/articles', '/posts'],
            'has_login_url'   => ['/login', '/signin', '/register', '/signup'],
        ];

        $urlList = [];
        foreach($routes as $route) {
            $url = is_array($route) ? ($route['url'] ?? $route['path'] ?? '') : (string)$route;
            if(!$url) continue;
            $urlList[] = $url;
            foreach($patterns as $flag => $keywords) {
                foreach($keywords as $kw) {
                    if(stripos($url, $kw) !== false) $result[$flag] = true;
                }
            }
        }

        $result['key_urls'] = array_slice(array_unique($urlList), 0, 20);

        if($result['has_shop_url'])    $result['route_features'][] = 'online shop/store (from URL structure)';
        if($result['has_api_url'])     $result['route_features'][] = 'public API endpoints';
        if($result['has_blog_url'])    $result['route_features'][] = 'blog/news section';
        if($result['has_login_url'])   $result['route_features'][] = 'user login/registration pages';
        if($result['has_account_url']) $result['route_features'][] = 'user account/profile pages';

        return $result;
    }

    protected function analyzeSamples(array $samplesData): array {
        $result   = ['sample_titles' => [], 'sample_descriptions' => [], 'business_context' => ''];
        $samples  = $samplesData['samples'] ?? $samplesData;
        if(!is_array($samples)) return $result;

        $titles = [];
        $descriptions = [];

        foreach(array_slice($samples, 0, 30) as $sample) {
            if(!is_array($sample)) continue;
            $title = $sample['title'] ?? $sample['name'] ?? '';
            if($title && strlen($title) > 2) $titles[] = $title;
            foreach(['summary', 'description', 'body', 'intro', 'excerpt'] as $field) {
                $val = $sample[$field] ?? '';
                if(is_string($val) && strlen($val) > 20) {
                    $descriptions[] = substr(strip_tags($val), 0, 150);
                    break;
                }
            }
        }

        $result['sample_titles']       = array_unique($titles);
        $result['sample_descriptions'] = array_slice($descriptions, 0, 5);
        if(!empty($titles)) {
            $result['business_context'] = "Sample content from the site: " . implode(', ', array_slice($titles, 0, 10));
        }

        return $result;
    }

    protected function detectFromLiveAPI(): array {
        $result  = ['features' => [], 'relevant_modules' => []];
        $modules = wire('modules');
        $fields  = wire('fields');

        $checks = [
            ['LoginRegister',        'user registration and login'],
            ['LoginRegisterPro',     'user registration and login'],
            ['Padloper',             'e-commerce / online store'],
            ['FormBuilder',          'contact and data collection forms'],
            ['Subscribe',            'newsletter subscription'],
            ['LanguageSupport',      'multi-language support'],
            ['LazyCron',             'scheduled background tasks'],
            ['SessionHandlerDB',     'database-backed session management'],
            ['CommentNotifications', 'user comments system'],
            ['PlausibleAnalytics',   'analytics tracking'],
        ];

        foreach($checks as $check) {
            list($module, $feature) = $check;
            if($modules->isInstalled($module)) {
                $result['features'][]         = $feature;
                $result['relevant_modules'][] = $module;
            }
        }

        $fileFields = $fields->getAll()->filter('type=FieldtypeFile');
        if($fileFields->count()) {
            $result['features'][] = 'file uploads (' . $fileFields->count() . ' file fields)';
        }

        if(!in_array('analytics and tracking', $result['features'])) {
            $result['features'][] = 'analytics and tracking';
        }

        return $result;
    }

    // =========================================================================
    // Validation
    // =========================================================================

    protected function getRequiredSections(string $documentSlug, string $jurisdiction): array {
        $base = [];

        switch($documentSlug) {
            case 'privacy-policy':
                $base = [
                    'Data Controller Identity'   => ['who we are', 'data controller', 'company name', 'registered address'],
                    'Data Collected'             => ['personal data', 'information we collect', 'data we collect'],
                    'Purpose of Processing'      => ['why we collect', 'how we use', 'purpose'],
                    'Data Retention'             => ['retention', 'how long', 'storage period'],
                    'Third Party Sharing'        => ['third part', 'sharing', 'disclose', 'processors'],
                    'User Rights'                => ['your rights', 'right to access', 'right to erasure', 'right to delete'],
                    'Contact Information'        => ['contact us', 'contact:', 'email:'],
                    'Security Measures'          => ['security', 'protect', 'encryption'],
                    'Cookies'                    => ['cookie', 'tracking', 'analytics'],
                    'Changes to Policy'          => ['changes', 'updates to this policy', 'we may update'],
                ];
                if(in_array($jurisdiction, ['eu_gdpr', 'uk_gdpr'])) {
                    $base['Legal Basis']         = ['legal basis', 'lawful basis', 'legitimate interest', 'consent'];
                    $base['Supervisory Authority'] = ['supervisory authority', 'ICO', 'DPA', 'data protection authority'];
                }
                if($jurisdiction === 'us_ccpa') {
                    $base['CCPA Rights']         = ['right to know', 'right to delete', 'opt-out', 'do not sell'];
                }
                break;

            case 'cookie-policy':
                $base = [
                    'What Are Cookies'    => ['what are cookies', 'cookies are', 'small text files'],
                    'Types of Cookies'    => ['strictly necessary', 'functional', 'analytics', 'marketing'],
                    'Third-Party Cookies' => ['third-party', 'third party cookies'],
                    'How to Manage'       => ['manage cookies', 'browser settings', 'opt-out'],
                    'Cookie Duration'     => ['session', 'persistent', 'expires', 'duration'],
                ];
                break;

            case 'terms-of-use':
                $base = [
                    'Acceptance'          => ['acceptance', 'agree to', 'by using', 'by accessing'],
                    'Prohibited Conduct'  => ['prohibited', 'you may not', 'forbidden'],
                    'Intellectual Property' => ['intellectual property', 'copyright', 'trademark'],
                    'Limitation of Liability' => ['limitation of liability', 'not liable', 'no warranty'],
                    'Governing Law'       => ['governing law', 'jurisdiction', 'dispute resolution'],
                    'Termination'         => ['termination', 'suspend', 'terminate'],
                    'Changes to Terms'    => ['changes to', 'we may update', 'we reserve the right'],
                ];
                break;

            case 'data-processing-agreement':
                $base = [
                    'Definitions'        => ['controller', 'processor', 'data subject'],
                    'Processing Details' => ['subject matter', 'nature', 'purpose of processing'],
                    'Processor Duties'   => ['processor shall', 'obligations', 'instructions'],
                    'Security Measures'  => ['security', 'technical', 'organizational measures'],
                    'Sub-processors'     => ['sub-processor', 'subprocessor'],
                    'Data Breach'        => ['breach', 'incident', 'notification'],
                    'Data Deletion'      => ['deletion', 'return', 'destroy'],
                    'Audit Rights'       => ['audit', 'inspection'],
                ];
                break;

            case 'ccpa-notice':
                $base = [
                    'Categories of PI'   => ['categories of personal information', 'identifiers'],
                    'Right to Know'      => ['right to know', 'request information'],
                    'Right to Delete'    => ['right to delete', 'deletion request'],
                    'Right to Opt-Out'   => ['opt-out', 'do not sell'],
                    'Non-Discrimination' => ['non-discrimination', 'not discriminate'],
                    'How to Submit'      => ['submit a request', 'how to exercise'],
                    'Response Timeline'  => ['45 days', 'response time'],
                ];
                break;

            case 'refund-policy':
                $base = [
                    'Eligibility'         => ['eligible', 'eligibility', 'qualify', 'conditions'],
                    'Refund Process'      => ['how to request', 'submit a request', 'process'],
                    'Processing Time'     => ['processing time', 'business days', 'within'],
                    'Non-Refundable'      => ['non-refundable', 'not eligible', 'excluded'],
                    'Contact Information' => ['contact us', 'email', 'support'],
                ];
                break;

            case 'disclaimer':
                $base = [
                    'General Disclaimer'       => ['no warranty', 'as-is', 'accuracy'],
                    'Limitation of Liability'  => ['not liable', 'limitation of liability'],
                    'External Links'           => ['external links', 'third-party'],
                    'Professional Advice'      => ['not professional advice', 'not legal advice', 'consult'],
                    'Changes'                  => ['changes', 'we reserve the right', 'update'],
                ];
                break;
        }

        return $base;
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    protected function getAI() {
        $context = wire('modules')->getModule('Context', ['noInit' => true]);
        if(!$context || !method_exists($context, 'ai')) return null;
        return $context->ai();
    }

    protected function parseFrontmatter(string $content): array {
        if(strpos($content, '---') !== 0) return [];
        $end = strpos($content, '---', 3);
        if($end === false) return [];
        $yaml = substr($content, 4, $end - 4);
        $data = [];
        foreach(explode("\n", $yaml) as $line) {
            if(strpos($line, ':') !== false) {
                list($key, $val) = explode(':', $line, 2);
                $data[trim($key)] = trim(trim($val), '"\'');
            }
        }
        return $data;
    }
}
